// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbzKZYghH__ZCL99VhkpXlDZn253OIwX0ZO_8IpGw39Z2xOpOImJu7obgGu_tFqwh24vBA/exec";
